---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revolut-user-service-staging
commonLabels:
  app: user-service-api

resources:
- ../base
- sa.yaml

patches:
- path: deployment.yaml

images:
  - name: asia-southeast1-docker.pkg.dev/tiinyplanet-379603/travelreys-api/travelreys-api
    newTag: 1.0.2 # 0.21.2