---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: api
      topologySpreadConstraints:
        - maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchLabels:
              app: api
      containers:
      - name: api
        env:
        - name: REVOLUT_USERS_SVC_HOST
          value: "0.0.0.0"
        - name: REVOLUT_USERS_SVC_PORT
          value: "8080"
        - name: REVOLUT_USERS_SVC_METRICS_PORT
          value: "8081"
        - name: REVOLUT_USERS_SVC_LOG_LEVEL
          value: "debug"
        - name: REVOLUT_USERS_SVC_CORS_ORIGIN
          value: "*"
        - name: REVOLUT_USERS_SVC_POSTGRES_HOST
          value: "users.ctmsm2isu4lq.eu-west-1.rds.amazonaws.com"
        - name: REVOLUT_USERS_SVC_POSTGRES_PORT
          value: "5432"
        - name: REVOLUT_USERS_SVC_POSTGRES_USERNAME
          value: "postgres"
        - name: REVOLUT_USERS_SVC_POSTGRES_PASSWORD
          value: "GORpsoeb5ajCOZ5K3wwB"
        - name: REVOLUT_USERS_SVC_POSTGRES_DATABASE
          value: "postgres"
        - name: REVOLUT_USERS_SVC_REDIS_URI
          value: "redis://default:t1$T#l>N7who4nWh^0lQqm9s0xj513LPUak7C6j^kEDi0r-2Ga5MNe!8b9<eSoooTwHDt1>!<XZfQED3Op75oZFo2mPwq!WLcEWMqJb9<ZzsXY7HYeswIJ16YUzRZD2!@clustercfg.users.vjad9t.euw1.cache.amazonaws.com:6379/0"
        - name: REVOLUT_USERS_SVC_REDIS_PASSWORD
          value: "t1$T#l>N7who4nWh^0lQqm9s0xj513LPUak7C6j^kEDi0r-2Ga5MNe!8b9<eSoooTwHDt1>!<XZfQED3Op75oZFo2mPwq!WLcEWMqJb9<ZzsXY7HYeswIJ16YUzRZD2!"

