apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revolut
commonLabels:
  app: api

resources:
- ../base
- ingress.yaml
- secret-provider-class.yaml

patches:
- path: deployment.yaml
- path: sa.yaml

images:
- name: revolut-user-service
  newName: 974860574511.dkr.ecr.eu-west-1.amazonaws.com/revolut-user-service
  newTag: 46d35e6-dirty
