---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revolut
commonLabels:
  app: api

resources:
- ../base
- ingress.yaml
- sa.yaml

patches:
- path: deployment.yaml

images:
  - name: revolut-user-service
    newName: 974860574511.dkr.ecr.eu-west-1.amazonaws.com/revolut-user-service
    newTag: f685ee1-dirty