apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revolut

resources:
- job.yaml

configMapGenerator:
- name: user-db-migrations
  files:
    - conf/db/migrations/V0__Initial.sql
