---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: agent
  namespace: platform-monitoring
spec:
  version: v2.39.1
  serviceAccountName: prometheus
  # serviceMonitorSelector:
  #   matchLabels:
  #     component: prometheus-agent
  # serviceMonitorNamespaceSelector:
  #   matchLabels:
  #     monitoring: prometheus-agent
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  replicas: 1
  logLevel: debug
  logFormat: logfmt
  scrapeInterval: 30s
  remoteWrite:
  # replace with your prometheus workspace url
  - url: def
    sigv4:
      region: eu-west-1
    queueConfig:
      maxSamplesPerSend: 1000
      maxShards: 200
      capacity: 2500
  containers:
  - name: prometheus
    args:
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.agent.path=/prometheus
    - --enable-feature=agent
    - --web.enable-lifecycle
