---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 2000
      serviceAccountName: api
      containers:
      - name: api
        image: revolut-user-service:v0.1.0
        command:
          - /app/server
          - '--log-level=debug'
        ports:
          - name: api
            containerPort: 8080
          - name: metrics
            containerPort: 8081
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
