---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revolut

commonLabels:
  app: api

resources:
- sa.yaml
- deployment.yaml
- service.yaml
- job.yaml

configMapGenerator:
- name: user-db-migrations
  files:
    - conf/db/migrations/V0__Initial.sql
