---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-api
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - interval: 15s
    targetPort: 8081
    path: /metrics
  namespaceSelector:
    matchNames:
    - revolut-user-service
  selector:
    matchLabels:
      app: api