---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  serviceAccountName: api
  template:
    spec:
      containers:
      - name: api
        image: revolut-user-service:v0.1.0
        command:
          - /app/server
          - '--log-level=debug'
        ports:
          - name: api
            containerPort: 8080
          - name: metrics
            containerPort: 8081
