apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-secrets

resources:
- ../base
- https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml
