apiVersion: v1
data:
  cluster.name: eks
  http.port: "2020"
  http.server: "On"
  logs.region: eu-west-1
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
