---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchLabels:
              app: api
      containers:
      - name: api
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: REVOLUT_USERS_SVC_HOST
          value: "0.0.0.0"
        - name: REVOLUT_USERS_SVC_PORT
          value: "8080"
        - name: REVOLUT_USERS_SVC_METRICS_PORT
          value: "8081"
        - name: REVOLUT_USERS_SVC_LOG_LEVEL
          value: "debug"
        - name: REVOLUT_USERS_SVC_CORS_ORIGIN
          value: "*"
        - name: REVOLUT_USERS_SVC_POSTGRES_HOST
          value: "users.ctmsm2isu4lq.eu-west-1.rds.amazonaws.com"
        - name: REVOLUT_USERS_SVC_POSTGRES_PORT
          value: "5432"
        - name: REVOLUT_USERS_SVC_POSTGRES_USERNAME
          value: "postgres"
        - name: REVOLUT_USERS_SVC_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-aws-secrets
              key: postgres-password
        - name: REVOLUT_USERS_SVC_POSTGRES_DATABASE
          value: "postgres"
        - name: REVOLUT_USERS_SVC_REDIS_URI
          value: "redis://clustercfg.users.vjad9t.euw1.cache.amazonaws.com:6379/0:6379/0"
        - name: REVOLUT_USERS_SVC_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-aws-secrets
              key: elasticache-password
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: user-service-aws-secrets
