---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: user-service-aws-secrets
spec:
  provider: aws
  parameters:
    region: eu-west-1
    objects: |
      - objectName: rds-users-password
        objectType: secretsmanager
      - objectName: elasticache-users-password
        objectType: secretsmanager
  secretObjects:
    - secretName: user-service-aws-secrets
      type: Opaque
      data:
      - key: postgres-password
        objectName: rds-users-password
      - key: elasticache-password
        objectName: elasticache-users-password
