---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-load-balancer-tls
  namespace: platform-cloud
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aws-load-balancer-controller-1.8.1
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: "v2.8.1"
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrakNDQXVLZ0F3SUJBZ0lSQUlha0VJM3ViQ25ESmlsVTdvWDlqSk13RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ2N4SlRBakJnTlZCQU1USEdGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQ2pMSVpZZHZ5aUJ1RXhwc3J3UUR0RWpXQVpDSi9aZ2VlekwxOGVodFNSb3Q4Y3dNTUltMXlDTTNSRwo2Mmk0U3FlbFdBL3Q3QnBPS1JDcmVDY3lMS29tc2lCRHBaZUhpUXlWenVlRGpkcEZLOWI1TERnUGI3WEN0aHYxCjJnRkZtNFhFT2pYeU1hbUlNQ0thWGpjYWVRTzVuZ3NpOVNQZzJwc0xXNUUzcTRBaHk0aXpSaW40VjBDWWJHZGsKS1ZhOHlST3NtYXZiQVUwc2EvbTZjaHM0WHRRRFJXSXZ2ZDQxeHdvRmpsVGcyNXRzWW4yWEhUOUdwMlQ4QndBUApvN2RNNlorSmRlbFU0anFpb29xNmNqNTdZell0TU1TUlkzWXFmV1ZUU1IwWUZ2VHNsUmEyUktVV0d2TnQzVGZDClVUU0NydTVYcVBuWVdjaWtib3NMUnB6WXBQK3hBZ01CQUFHamdnRWNNSUlCR0RBT0JnTlZIUThCQWY4RUJBTUMKQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBdwpId1lEVlIwakJCZ3dGb0FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd2diY0dBMVVkRVFTQnJ6Q0JySUl3CllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdGQyVmlhRzl2YXkxelpYSjJhV05sTG5Cc1lYUm1iM0p0TFdOc2IzVmsKZ2pSaGQzTXRiRzloWkMxaVlXeGhibU5sY2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0d4aGRHWnZjbTB0WTJ4dgpkV1F1YzNaamdrSmhkM010Ykc5aFpDMWlZV3hoYm1ObGNpMTNaV0pvYjI5ckxYTmxjblpwWTJVdWNHeGhkR1p2CmNtMHRZMnh2ZFdRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBbXYKYmJOZDRSU1ROaWFic2xEK2UxQUxDN3UySTVWMzVURDl3dlpmMG1kS2VRVzJWcFZNaGExSnNkVmovMWhrRmpFTgp4bGJmUHdhakJkSGNXeCsrQjZISWtWb1U4MytaQzh2MUxSTGN4enlxbDlJVVpJSzBRdjlpd3VtMEloTDVtUXJ1CjlrUjJneVdnNTFnTUJjSEJlMHk1dlVLMnRSTG1TdDUwNmdMaXNZM3g0WEJiMkVVeGpSMnpwbkNvNFpPMkZBdzUKRmwxYWkrSEViWW1ybnZGQ20zeEptTEkyZlVtYmRmcTFkdzRkYlJWVEVjcHorNVRtQWxyQnZ3NmZhY0NVVjBLcwprN0VNdHcrRytFUjZNYVBqbklSU0h3UTJUeEZBRFhOak15bkk0bjdCVU1qRnJVbzh6SEN3RjRjMjNyenlkNkRhClgzSXJ5dzlUSDdza1FIUkdFUkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBb3l5R1dIYjhvZ2JoTWFiSzhFQTdSSTFnR1FpZjJZSG5zeTlmSG9iVWthTGZITURECkNKdGNnak4wUnV0b3VFcW5wVmdQN2V3YVRpa1FxM2duTWl5cUpySWdRNldYaDRrTWxjN25nNDNhUlN2VytTdzQKRDIrMXdyWWI5ZG9CUlp1RnhEbzE4akdwaURBaW1sNDNHbmtEdVo0TEl2VWo0TnFiQzF1Uk42dUFJY3VJczBZcAorRmRBbUd4blpDbFd2TWtUckptcjJ3Rk5MR3Y1dW5JYk9GN1VBMFZpTDczZU5jY0tCWTVVNE51YmJHSjlseDAvClJxZGsvQWNBRDZPM1RPbWZpWFhwVk9JNm9xS0t1bkkrZTJNMkxUREVrV04yS24xbFUwa2RHQmIwN0pVV3RrU2wKRmhyemJkMDN3bEUwZ3E3dVY2ajUyRm5JcEc2TEMwYWMyS1Qvc1FJREFRQUJBb0lCQURCUDRvY1cwNzMxWTMrYgo3c0lyZ21ETnF3SStkM1dpN01NMDUyaldhdUdqNDROVDMyc1E5TmJuL1NseVVkTWU1M3doRXJaVERZYk95Y3k3CkNuL2trWXhiZVFvT1lVc1QzTklPTEtYYXZpRjAxWFY1RGpBajF5RUxZa1BzaEN2ajNEczVNUGZBbEgxcUl4U3AKaUk4aC9XUmIwdGhLMUpDaXFQMDM0MHNrVUEreEJtcmQxRndDenlVVnFLdGpQekxZYTQ3aXdYN0o1aHFSc1NtdQplNjJMWTNtUWhnYnpQV3Z0anhMb3diRklVODFNWjRFNWs3ZDZGNG1YMndaYzFqOUxJNUMyL3Y4KzU0dzdlb3VhClhDZ0x6bzhab1pNRmRYOGNublpyTCtyTkJlWlJrOUlmVGViL3h2NWtnZnFvVW5kUGZIdnhtNTRSRndyVGNodnQKdzBaRnEwRUNnWUVBeENEWnlmeU9pa0lLcXBWRU13RmpUOWRoeThHOVFDd0d1dTFxMTZPcVFySzk1c1JsR21FQwpydngxaldMR2pEWVdtZ1gzREFuQVZqM0Zpb25XUEU2Wit3QUpDTHg0dmNLMEprNFNCdGxoYmsyT0xDYWIvYmViCi9rcVNNLzFxUjJMaVZ2K01mOUxxOFRZclI1UnhtVmE4SFBsQmVwSWVRQmVmcTJuWjJNRWl2NlVDZ1lFQTFQeFYKc1dNdE05VUdoZmF2emh0eTM2YzVDQWIyTXd0ZitMb2o5RkRubzFtb3JuVVh6QVdZV3oyT0ZibzNabXg5djV0NgpkekgwYkF5aGpNUWhBdThZSkJjV0JITi91SkpyeTlFbzNLeUNXbkFFdmxvZHBEQ1I5WHJraHk5TDFMUXY1YmJJCm5EdjlBUWNtblJMRlQ0QWwyZ2Z2WkhoYmNqcHpNZmJRQ3JOK0FoMENnWUVBd2FwV3BGZFpRVGpaWTN3bGJlQXUKK3NZSmNiUUxkblNDNk01THRFZU9kbklkaHVQam1kcTFWYWxCUXEySXRTY3J4a2VoblNkNzN5ejhCVUw2WTI2UwpLZ0hzNmMyQnhJK2dhRHFySGt4Rkl6QTk5V2JpbmZSU2V4V1RyUGJOblZRTmdDNnp3L3kzdGh2eFBLdGVTVFlXClp0M1NSSUJJa3ExQkkzaFFmdktucDJrQ2dZQUI0MTdMSE1yNHk2bXNKRnk0b2d1cHFlemFnbDFLWkk1c1FSSXkKaDBrV2JLUVBMK0NQSVhtUlRZRmw5ZW1wMGNwbm1YUkRmRURqZUZVeVQwYlBwTmo4OE90MERLWVVOOUFXMVhyYwpRZmRCMy81YXhhZS9uZUtkWDRLSkpFVXkxSW9jS2p1ckR1a1dTajd3WTRzMlFqZVRzRUJTRHJNWTF5WFFTcFRiCmsyM0pqUUtCZ1FDRFhTZ05TYWhYc2hlQWR5eFJCUVduY09iUW0xSlBwZWVCdUJ1WFlxdnNQa0RhTXFvMVZqNHkKMzlNQ05STGFCTWFrRDdYaWV0ZzFPZGJIRlZ6UEVWY0dWTHA4YUdEMVFCZmJDUlVmUHVuYU1WdkYvL2VLWlRjdwpBRUVNUTJPdEhVdm1zZHcvK2JkYjQrSVdSSW1Gbk5YbVVMdGhCOTlmT0syRnZXcU9GRmlvNUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aws-load-balancer-controller-1.8.1
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: "v2.8.1"
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    
    service:
      name: aws-load-balancer-webhook-service
      namespace: platform-cloud
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  namespaceSelector:
    matchExpressions:
    
    - key: elbv2.k8s.aws/pod-readiness-gate-inject
      operator: In
      values:
      - enabled
    
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    
    service:
      name: aws-load-balancer-webhook-service
      namespace: platform-cloud
      path: /mutate-v1-service
  failurePolicy: Fail
  name: mservice.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - services
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    
    service:
      name: aws-load-balancer-webhook-service
      namespace: platform-cloud
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: mtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
---
# Source: aws-load-balancer-controller/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aws-load-balancer-controller-1.8.1
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: "v2.8.1"
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    
    service:
      name: aws-load-balancer-webhook-service
      namespace: platform-cloud
      path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
  failurePolicy: Fail
  name: vingressclassparams.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressclassparams
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    
    service:
      name: aws-load-balancer-webhook-service
      namespace: platform-cloud
      path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: vtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU56TzJaNUdmUFJHdjBqWDZ2WVVYQ3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOREEyTVRjeE16SXhOVEJhRncwek5EQTJNVFV4TXpJeE5UQmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURndVhkaFF3bm43SHZvcjhCS0dJY2lBUkg0WmQ1bkVvbHgyOVJqLzBsWEU0VTAvWjRQTXZUagpNc2dqVEdQOFRhdUxBRW4zZU91cC81ZWU2NWdzSFBnaUdFazFmTU8zQklqN0lBZjh6MEJlc1F3ZUZhdzhLTHZrCjg1QlZXUEN2M0VZckMyRnVxUUI1YUFuK2ZMWjhsWkRPMGs3d1pEZWtGTktxZ0NlME9tQ0c5Y2huN0g5N09vVVEKaUVJK3Noc2lzcENoL0FDNVBSRGVWVGQzcmtuYVlTQ0ZHUnRNaDN0MDRUc1FSWlBLeVpETFc5d2xyNXBpbk42cwpyWEY1YmFEMHAwN0R5M0gzcjZ6Zm9FM0JRWWtLUVV2QlZoQk5oZkVYTUpJZTQ2MmQrUGtVK3BxU041Q1k0cCt5CmtrMzV5QmFaVUZDcVR6SjViTGNwZVIyRjBqRXBwR2R0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVVVdXNFl2SW40RmhQTXp3YmR2eE00V2dDdklzd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSUhsT29EZ2FtNjlkK2lGUzVMcW1yUGtzYjJZYThUWmE3alllTytDVUFjeGFZT3l6Ky9wR1ZtVFJRRlkKOWxwY1B1cnB1SDQ2QVB0UEdCcFcyankwUW80ZWFDUW9lbFZTVENzV3BYNzlsOFZkaXNyck5sRW5tR1RPbnUxVwpMYVExSVZ2OG5samtBOUp6anp3ZVFwK2lvWXlwaTVJczlEK2sxMGNUMVg4c3lJdEdrTHpYZkw1Z0tObjRPM2dyCkd1akJ3M3cwQmNGRTBLK2FDR3pIbGVnRWV3TFhyakxLUmZrem83WG1sL0JxaHptMjVNRm9WdlVxZmt5Rk53R1AKcGFscmszUGFXSFV5WHVYNXRzKzI2bXEyRFRwdjBCby9kUTYweTFJN3VhNDhKd1NIUTBSRjdCOFI4MjhYMnZHSQozaDAxUWpFaEFkRVEwcVM3ZWVIK1JJRTMrREU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    
    service:
      name: aws-load-balancer-webhook-service
      namespace: platform-cloud
      path: /validate-networking-v1-ingress
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vingress.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
