---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ingress

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.6.4/deploy/static/provider/cloud/deploy.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-nginx
