---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plaform-ingress

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.6.4/deploy/static/provider/cloud/deploy.yaml

patches:
  - |-
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: ingress-nginx
